- hosts: localhost
  connection: local
  user: "{{ username }}"
  become: true
  vars:
    docker_users:
      - "{{ username }}"
  roles:
    - packages_base
    - packages_embedded
    - geerlingguy.docker
    - git
    - tmux
    - ohmyzsh
    - vscodium
