- hosts: localhost
  connection: local
  user: "{{ username }}"
  become: false
  vars:
    docker_users:
      - "{{ username }}"
  roles:
    - packages_base
    - packages_embedded
    - role:  geerlingguy.docker
      become: true
    - git
    - tmux
    - ohmyzsh
    - vscodium
    # The messages role should stay as the last one.
    - messages
