- name: Install embedded development packages
  ansible.builtin.dnf:
    name:
    - '@development-tools'
    - minicom
    - openocd
    state: latest

- name: Allow user to use serial device without sudo
  ansible.builtin.user:
    name: "{{ username }}"
    groups: dialout
    append: yes

