---
- name: Install Zsh and git
  dnf:
    name:
    - git
    - zsh
    state: present

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ home_dir }}/.oh-my-zsh"

- name: Cloning zsh-256color plugin
  git:
    repo: https://github.com/chrissicool/zsh-256color
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-256color"

- name: Cloning zsh-completions
  git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"

- name: Creating new ~/.zshrc from template
  template:
    src: "{{ zkbd_template }}"
    dest: "{{ home_dir }}/.zkbd/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Ensure ~/.zkbd exists
  file:
    path: "{{ home_dir }}/.zkbd"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Creating new ~/.zkbd/xterm-256color-:0 from template
  template:
    src: "{{ zshrc_template }}"
    dest: "{{ home_dir }}/.zkbd/xterm-256color-:0"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Fix ownership
  command: "chown -R {{ username }}:{{ username }} {{ home_dir }}/.oh-my-zsh"

- name: Set Zsh as defult shell
  command: "chsh -s /bin/zsh {{ username }}"
