- name: Install base packages
  ansible.builtin.dnf:
    name:
      - curl
      - gparted
      - htop
      - thunderbird
      - tree
      - python3
      - python3-pip
      - python3-virtualenv
      - libreoffice
      - gpg
      - tmux
      - pre-commit
      - util-linux-user
      - openssl
    state: latest
- name: Clone markdown linter
  vars:
    repo_url: "https://github.com/3mdeb/hooks.git"
    repo_path: "{{ home_dir }}/.config/3mdeb-hooks"
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_path }}"
    clone: yes
  become: true
  become_user: "{{ username }}"
- name: Create ~/.local/bin directory for markdown.sh script
  file:
    path: "{{ home_dir }}/.local/bin"
    state: directory

- name: Create symlink for markdown.sh script
  vars:
    symlink_src: "{{ home_dir }}/.config/3mdeb-hooks/markdown.sh"
    symlink_dest: "{{ home_dir }}/.local/bin/markdown.sh"
  file:
    src: "{{ symlink_src }}"
    dest: "{{ symlink_dest }}"
    state: link
    force: yes

- name: Check the model of the CPU
  shell: |
    CPU_MODEL=$(grep -m1 model /proc/cpuinfo)
    echo "${CPU_MODEL##*: }"
  register: cpu_model

- name: Install drivers for older CPUS
  vars:
    model: "{{cpu_model.stdout}}"
  shell: |
    sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    sudo dnf swap ffmpeg-free ffmpeg --allowerasing
    sudo dnf install libva-intel-driver
  when: (model | int) < 60
