- name: Install base packages
  become: true
  dnf:
    name:
      - curl
      - gparted
      - htop
      - thunderbird
      - tree
      - python3
      - python3-pip
      - python3-virtualenv
      - libreoffice
      - gpg
      - tmux
      - pre-commit
      - util-linux-user
      - openssl
    state: latest

- name: Create ~/.local/bin directory if it does not exist
  file:
    path: "{{ home_dir }}/.local/bin"
    state: directory
    recurse: yes

- name: Clone markdown linter
  vars:
    repo_url: "https://github.com/3mdeb/hooks.git"
    repo_path: "{{ home_dir }}/.config/3mdeb-hooks"
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_path }}"
    clone: yes

- name: Create symlink for markdown.sh script
  vars:
    symlink_src: "{{ home_dir }}/.config/3mdeb-hooks/markdown.sh"
    symlink_dest: "{{ home_dir }}/.local/bin/markdown.sh"
  file:
    src: "{{ symlink_src }}"
    dest: "{{ symlink_dest }}"
    state: link
    force: yes

- name: Check the generation of GPU
  become: true
  shell: |
    if test -d "/sys/kernel/debug/dri/1"
    then
      cat /sys/kernel/debug/dri/1/i915_gpu_info | grep "graphics version" | cut -d ' ' -f 3
    else
      cat /sys/kernel/debug/dri/0/i915_gpu_info | grep "graphics version" | cut -d ' ' -f 3
    fi
  register: gpu_gen

- name: Install RPM Fusion repositories (for Intel CPUs 7th or older generations)
  become: true
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
    state: present
  when: (gpu_gen.stdout | int) <= 7

- name: Swap ffmpeg-free with ffmpeg (for Intel CPUs 7th or older generations)
  become: true
  dnf:
    name: ffmpeg
    allowerasing: true
    state: present
    disablerepo: ffmpeg-free
  when: (gpu_gen.stdout | int) <= 7

- name: Install libva-intel-driver (for Intel CPUs 7th or older generations)
  become: true
  dnf:
    name: libva-intel-driver
    state: present
  when: (gpu_gen.stdout | int) <= 7
