---
- name: Import VSCodium RPM release key
  ansible.builtin.rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

- name: Install /etc/yum.repos.d/vscodium.repo 
  template:
    src: "vscodium.repo.j2"
    dest: "/etc/yum.repos.d/vscodium.repo"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Install VSCodium
  dnf:
    name: codium
    state: present
