---
- name: Install tmux
  become: true
  apt:
    name: tmux
    state: present

- name: Install ~/.tmux.conf from template
  template:
    src: "{{ tmux_template }}"
    dest: "{{ home_dir }}/.tmux.conf"
    mode: '0644'
